### ISSUE TITLE
Timeouts not working with HTTP2

### ISSUE THREAD

**Issue by EdgardoSchiffer** [tiagohm/restio#16]
Hello, I been doing some requests testing how my app would behave if there is no answer or connectivity with remote, when I try to set a timeout with http2 enable it doesn't work and the request keeps alive like forever, this is the client I'm using:

final client = Restio(
  http2: true, 
  connectTimeout: Duration(seconds: 5), 
  receiveTimeout: Duration(seconds: 5), 
  writeTimeout: Duration(seconds: 5),
  followRedirects: true,
  maxRedirects: 1,
  verifySSLCertificate: false,
  dns: DnsOverUdp.google(),
  interceptors: [MyInterceptor()],
);

On http2: false works fine.

**Comment by tiagohm** [comment]
Hello, thanks for filling this issue.

I don't know when I will publish a new release, but you can test getting a snapshot version:

```yaml
 restio:
    git:
      url: git://github.com/tiagohm/restio.git
      ref: bb44cf8a1084103f6d21e46b83dc255bced178dc
```
